### PR TITLE
fix not running

### PR DESCRIPTION
**Pull request by Gamediamond3757**
do it

### CODE REVIEW

**Review by Nagol12344 — COMMENTED** [review]
i dont see a change here, so i have no reason to push it

**Comment by Gamediamond3757** [comment]
the name is chage

**Comment by Nagol12344** [comment]
i can do that on my own, i dont see a change to fix run

**Comment by Nagol12344** [comment]
i will have to close this now

**Review by Nagol12344 — COMMENTED** [review]
changes something i fixed, and usless edits to main.py

**Pull request closed without merging**
